src/Entity/Critere.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use JMS\Serializer\Annotation as Serializer;


/**
 * @ORM\Entity(repositoryClass="App\Repository\CritereRepository")
 */
class Critere
{

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     * @Serializer\Groups({"demande"})
     */
    private $id;


    /**
     * @ORM\Column(type="string", length=10)
     *  @Serializer\Groups({"demande"})
     */
    private $nb_m_carre;

    /**
     * @ORM\Column(name="lieu", type="string", columnDefinition="enum('bureau', 'domicile')")
     * @Serializer\Groups({"demande"})
     */
    private $lieu;

    /**
     * @ORM\Column(type="integer")
     * @Serializer\Groups({"demande"})
     */
    private $annee_constr;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Serializer\Groups({"demande"})
     */
    private $plan_lieu;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Serializer\Groups({"demande"})
     */
    private $photo_lieu;

    /**
     * @ORM\Column(type="string")
     * @Serializer\Groups({"demande"})
     */
    private $orientation;

    /**
     * @ORM\Column(type="string", length=20)
     * @Serializer\Groups({"demande"})
     */
    private $titre_diagnostic;


    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Diagnostic", mappedBy="critere", cascade={"persist", "remove"})
     */
    private $diagnostic;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="critere")
     */
    private $user;

       
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNbMCarre(): ?string
    {
        return $this->nb_m_carre;
    }

    public function setNbMCarre(string $nb_m_carre): self
    {
        $this->nb_m_carre = $nb_m_carre;

        return $this;
    }

    public function getLieu(): ?string
    {
        return $this->lieu;
    }

    public function setLieu(string $lieu): self
    {
        $this->lieu = $lieu;

        return $this;
    }

    public function getAnneeConstr(): ?int
    {
        return $this->annee_constr;
    }

    public function setAnneeConstr(int $annee_constr): self
    {
        $this->annee_constr = $annee_constr;

        return $this;
    }

    public function getPlanLieu(): ?string
    {
        return $this->plan_lieu;
    }

    public function setPlanLieu(?string $plan_lieu): self
    {
        $this->plan_lieu = $plan_lieu;

        return $this;
    }

    public function getPhotoLieu(): ?string
    {
        return $this->photo_lieu;
    }

    public function setPhotoLieu(?string $photo_lieu): self
    {
        $this->photo_lieu = $photo_lieu;

        return $this;
    }

    public function getOrientation(): ?string
    {
        return $this->orientation;
    }

    public function setOrientation(?string $orientation): self
    {
        $this->orientation = $orientation;

        return $this;
    }

    public function getTitreDiagnostic(): ?string
    {
        return $this->titre_diagnostic;
    }

    public function setTitreDiagnostic(string $titre_diagnostic): self
    {
        $this->titre_diagnostic = $titre_diagnostic;

        return $this;
    }


    public function getDiagnostic(): ?Diagnostic
    {
        return $this->diagnostic;
    }

    public function setDiagnostic(Diagnostic $diagnostic): self
    {
        $this->diagnostic = $diagnostic;

        // set the owning side of the relation if necessary

        if ($diagnostic->getCritere() !== $this) {
            $diagnostic->setCritere($this);

        }

        return $this;
    }


    public function getUser(): ?User


    {
        return $this->user;
    }


    public function setUser(?User $user): self

    {
        $this->user = $user;

        return $this;
    }

}

src/Entity/Diagnostic.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\DiagnosticRepository")
 */
class Diagnostic
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="date")
     */
    private $date;

    /**
     * @ORM\Column(type="boolean")
     */
    private $statut_paiement;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $prix;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $expertise;

    /**
     * @ORM\Column(type="boolean")
     */
    private $statut_expertise;

   
    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Critere", inversedBy="diagnostic", cascade={"persist", "remove"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $critere;

    

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getStatutPaiement(): ?bool
    {
        return $this->statut_paiement;
    }

    public function setStatutPaiement(bool $statut_paiement): self
    {
        $this->statut_paiement = $statut_paiement;

        return $this;
    }

    public function getPrix(): ?int
    {
        return $this->prix;
    }

    public function setPrix(?int $prix): self
    {
        $this->prix = $prix;

        return $this;
    }

    public function getExpertise(): ?string
    {
        return $this->expertise;
    }

    public function setExpertise(?string $expertise): self
    {
        $this->expertise = $expertise;

        return $this;
    }

    public function getStatutExpertise(): ?bool
    {
        return $this->statut_expertise;
    }

    public function setStatutExpertise(bool $statut_expertise): self
    {
        $this->statut_expertise = $statut_expertise;

        return $this;
    }

    public function getCritere(): ?Critere
    {
        return $this->critere;
    }

    public function setCritere(Critere $critere): self
    {
        $this->critere = $critere;

        return $this;
    }
}

src/Controller/UserController.php
<?php


namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\User;
use App\Entity\Diagnostic;
use App\Repository\UserRepository;
use Doctrine\ORM\EntityManagerInterface as EMI;
use Symfony\Component\HttpFoundation\Request;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use App\Form\UserSubsFormType;
use App\Security\LoginFormAuthenticator;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;
use Symfony\Component\Security\Guard\GuardAuthenticatorHandler;
use App\Repository\DiagnosticRepository;
use App\Repository\CritereRepository;
use Symfony\Component\Form\FormView;
use JMS\Serializer\SerializerBuilder;
use JMS\Serializer\SerializationContext;
use JMS\Serializer\SerializerInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Symfony\Component\Security\Csrf\TokenGenerator\TokenGeneratorInterface;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;
use Symfony\Component\DependencyInjection\ExpressionLanguageProvider;
use Symfony\Component\Routing\Generator\UrlGeneratorInterface;
use Swift_Mailer;



class UserController extends AbstractController
{
  
  /**
     * @Route("/inscription", name="user_subs")
      * @Security("not is_granted('ROLE_USER')")
     */
public function register(Request $request, UserPasswordEncoderInterface $passwordEncoder, GuardAuthenticatorHandler $guardHandler, LoginFormAuthenticator $authenticator): Response
    {
        $user = new User();
        $form = $this->createForm(UserSubsFormType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            // encode the plain password
            $user->setPassword(
                $passwordEncoder->encodePassword(
                    $user,
                    $form->get('password')->getData()
                )
            );
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($user);
            $entityManager->flush();

            // do anything else you need here, like send an email

            return $guardHandler->authenticateUserAndHandleSuccess(
                $user,
                $request,
                $authenticator,
                'main' // firewall name in security.yaml
            );
        }

        return $this->render('user/index.html.twig', [
            'UserSubsForm' => $form->createView(),
          
        ]);
    }

    /**
     * @Route("/user", name="compte_user")
     * @Security("is_granted('ROLE_USER')")
     */
    public function infos_user(UserRepository $ur, DiagnosticRepository $dr, CritereRepository $cr)
    {
    $user = $ur->findAll();
    $diagnostic = $dr->findAll();
    $critere = $cr->findAll();

        return $this->render('user/compte_user.html.twig', [ "user" => $ur,"diagnostic" => $dr, "critere" => $cr ]);
    }

   /**
 * @Route("/user/modifier/{id}", name="user_modifier")
    * @Security("is_granted('ROLE_USER')")
 */
public function modifier(UserRepository $ur, Request $request, EMI $em, int $id )
{
    $bouton = "update";
    $userAmodifier = $ur->find($id);

    // Récupération des données envoyées par le formulaire
    if($request->isMethod("POST")){ 
        $nom = $request->request->get('nom');
        $prenom = $request->request->get('prenom');
        $mdp = $request->request->get('password');

        // Création d'un objet Record avec les données récupérées
        $userAmodifier->setNom($nom);
        $userAmodifier->setPrenom($prenom);
        $userAmodifier->setPassword($mdp);
        
        // Enregistrement en BDD
        $em->persist($userAmodifier);
        $em->flush();

        return $this->redirectToRoute("compte_user");

    }
    return $this->render('user/modif_user.html.twig', ["user" => $userAmodifier, "bouton" => $bouton]);
} 


    /**
     * @Route("/user/supprimer/{id}", name="user_supprimer")
     * @Security("is_granted('ROLE_USER')")
     */

    public function supprimer(UserRepository $ur, Request $request, EMI $em, int $id)
    {

        $userAsupprimer = $ur->find($id);

            // Enregistrement en BDD
            $em->remove($userAsupprimer);
            $em->flush();


            // Ajout de message Alert
            $this->addFlash(
                'info',
                'Etes vous sur de bien vouloir supprimer votre compte?'
            );        
        return $this->render('user/supprimer_user.html.twig', ["user" => $userAsupprimer,]);
    }


    /**
    * @Route("/admin/gestion", name="gestion")   
    * @IsGranted("ROLE_ADMIN") 
    */
    public function compte_admin(UserRepository $ur, DiagnosticRepository $dg, CritereRepository $cr)
    {
        $clients=$ur->findAll();
        $diagnostics=$dg->findAll();
        $demandes=$cr->findAll();
        
        return $this->render("user/compte_admin.html.twig",["listeclient" => $clients, "listediag" => $diagnostics, "listedemande" => $demandes] );
    }
        
    /**
     * @Route("/admin/user/ajouter", name="user_add")
     * @IsGranted("ROLE_ADMIN")
     */
    public function add(UserRepository $ur, EMI $em, Request $request)
    {
        $bouton = "add";

        if($request->isMethod("POST")){ 
            $nom = $request->request->get('nom');
            $prenom = $request->request->get('prenom');
            $email = $request->request->get('email');
            $mdp = $request->request->get('password');
            $mdp = password_hash($mdp, PASSWORD_DEFAULT);
            $user = new User; 
            $user->setEmail($nom);
            $user->setPassword($mdp);

            $em->persist($user);
            $em->flush();

            return $this->redirectToRoute("gestion");

        }else{
            return $this->render('user/compte_admin.html.twig', ["bouton" => $bouton]); 
        }
    }

    /**
     * @Route("/admin/user/modifier/{id}", name="user_update")
     * @IsGranted("ROLE_ADMIN")
     */
    public function update(UserRepository $ur, Request $request, EMI $em, int $id)
    {
        $bouton = "update";
        $userAmodifier = $ur->find($id);

        if($request->isMethod("POST")){ 
            $nom = $request->request->get('nom');
            $prenom = $request->request->get('prenom');
            $email = $request->request->get('email');
            // trim supprime les espaces au début et à la fin d'une chaîne de caractères
            $mdp = trim($request->request->get('password'));
            if($mdp){
                $mdp = password_hash($mdp, PASSWORD_DEFAULT);
                $userAmodifier->setPassword($mdp);
            }
            
            $userAmodifier->setNom($nom);
            $userAmodifier->setPrenom($prenom);
            $userAmodifier->setEmail($email);

            $em->persist($userAmodifier);
            $em->flush();

            return $this->redirectToRoute("gestion");

        }
        return $this->render('user/formulaire.html.twig', ["user" => $userAmodifier, "bouton" => $bouton]); 

    }


    /**
     * @Route("/admin/user/supprimer/{id}", name="user_delete")
     * @IsGranted("ROLE_ADMIN")
     */
    public function delete(UserRepository $ur, Request $request,EMI $em, int $id)
    {
        $bouton = "delete";
        $userAsupprimer = $ur->find($id);

        if ($request->isMethod("POST")){
            $em->remove($userAsupprimer);
            $em->flush();
            return $this->redirectToRoute("gestion");
        }
        return $this->render('user/formulaire.html.twig', ["user" => $userAsupprimer, "bouton" => $bouton]);
    } 
    /**
     * @Route("/forgotten_password", name="app_forgotten_password")
     */
    public function forgottenPassword(Request $request, UserPasswordEncoderInterface $encoder, Swift_Mailer $mailer, TokenGeneratorInterface $tokenGenerator, EMI $em): Response
    {

        if ($request->isMethod('POST')) {

            $email = $request->request->get('email');

            $em = $this->getDoctrine()->getManager();
            $user = $em->getRepository(User::class)->findOneBy(['email' => $email]);
            /* @var $user User */
            $token = $tokenGenerator->generateToken();

            if ($user === null) {
                $this->addFlash('danger', 'Email Inconnu');
            }
            else{
                $user->setResetToken($token);
                $em->flush();
        

            $url = $this->generateUrl('app_reset_password', array('token' => $token), UrlGeneratorInterface::ABSOLUTE_URL);

            $message = (new \Swift_Message('Mot de passe oublié'))
                ->setFrom('kathleen.stassart@gmail.com')
                ->setTo($user->getEmail())
                ->setBody(
                    " Voici le lien pour générer votre nouveau mot de passe : " . $url,
                    'text/html'
                );

            $mailer->send($message);

            $this->addFlash('success', 'Mail envoyé');
            return $this->redirectToRoute('accueil');
        }
    }

        return $this->render('security/forgotten_password.html.twig');
    }

     /**
     * @Route("/reset_password/{token}", name="app_reset_password")
     */
    public function resetPassword(Request $request, string $token, UserPasswordEncoderInterface $passwordEncoder, EMI $em)
    {

        if ($request->isMethod('POST')) {
            $em = $this->getDoctrine()->getManager();

            $user = $em->getRepository(User::class)->findOneBy(['resetToken' => $token]);;
            /* @var $user User */

            if ($user === null) {
                $this->addFlash('danger', 'Le chemin est inconnu');
            }

            $user->setResetToken(null);
            $user->setPassword($passwordEncoder->encodePassword($user, $request->request->get('password')));
            $em->flush();

templates/user/compte_admin.html.twig
{% extends 'base.html.twig' %}

{% block title %} e-Feng Shui {% endblock %}

{% block body %}
<div id="blocTgestion">
    <h1 class="titre">{% trans %}MANAGEMENT{% endtrans %}</h1>
    <div id="load"></div>
</div>
<div class="blocAdmin">
    <aside>
        <div class="btn-group-vertical">
            <button type="button" class="btn btn-secondary"id="clientsList">{% trans %}Customer List{% endtrans %}</button>
            <button type="button" class="btn btn-secondary" id="diagList">{% trans %}Diagnostic List{% endtrans %}</button>
            <button type="button" class="btn btn-secondary" id="demandesList">{% trans %}Request List{% endtrans %}</button>
        </div>
    </aside>
    <div id="blocResultat">
        <div class="flex-column-reverse" id="tabUser">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-body">
                        <table class="table table-bordered">
                            <thead class="entete"> 
                                <tr>
                                    <th>{% trans %}N°customer{% endtrans %}</th>
                                    <th>{% trans %}First name{% endtrans %}</th>
                                    <th>{% trans %}Name{% endtrans %}</th>
                                    <th>{% trans %}Email{% endtrans %}</th>
                                    <th>{% trans %}Roles{% endtrans %}</th>
                                    <th colspan=2>{% trans %}Actions{% endtrans %}</th>
                                </tr> 
                            </thead>
                            <tbody class="corps">
                                {% for client in listeclient %}
                                    <tr>
                                        <td>{{client.id}}</td>
                                        <td>{{client.nom}}</td>
                                        <td>{{client.prenom}}</td>
                                        <td>{{client.email}}</td>
                                        <td>{{client.roles|join(", ")}}</td>
                                        <td><a href='id'><i class='fa fa-pen'></i></a></td>
                                        <td><a href='id'><i class='fa fa-trash'></i></a></td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <div class="flex-column-reverse" id="tabDiagnostic">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-body">
                        <table class="table table-bordered">
                            <thead class="entete"> 
                               <tr>
                                    <th>{% trans %}N°diagnostic{% endtrans %}</th>
                                    <th>{% trans %}N°file{% endtrans %}</th>
                                    <th>{% trans %}Title{% endtrans %}</th>
                                    <th>{% trans %}Date{% endtrans %}</th>
                                    <th>{% trans %}Price{% endtrans %}</th>
                                    <th>{% trans %}Expertise{% endtrans %}</th>
                                    <th>{% trans %}Send{% endtrans %}</th>
                               </tr> 
                            </thead>
                            <tbody class="corps">
                                {% for diag in listediag %}
                                    <tr>
                                        <td>{{diag.id}}</td>
                                        <td>{{diag.critere.id}}</td>
                                        <td>{{diag.critere.titreDiagnostic}}</td>
                                        <td>{{diag.date|date("d/m/Y")}}</td>
                                        <td>{{diag.prix}}</td>
                                        <td><a href='' download='diactostic.pdf'><i class='fas fa-file-download'> </i></a></td>
                                        <td><a href='#'><button><i class='fas fa-envelope'></i></button></a></td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <div class="flex-column-reverse" id="tabCritere">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-body">
                        <table class="table table-bordered">
                            <thead class="entete">
                                <tr> 
                                    <th>{% trans %}N°file{% endtrans %}</th>
                                    <th>{% trans %}Title{% endtrans %}</th>
                                    <th>{% trans %}M²{% endtrans %}</th>
                                    <th>{% trans %}Place{% endtrans %}</th>
                                    <th>{% trans %}Year{% endtrans %}</th>
                                    <th>{% trans %}Place plan{% endtrans %}</th>
                                    <th>{% trans %}Photo{% endtrans %}</th>
                                    <th>{% trans %}Orientation{% endtrans %}</th>
                                    <th colspan=2>{% trans %}Actions{% endtrans %}</th>
                                </tr> 
                            </thead>
                            <tbody class="corps">
                                {% for crit in listedemande %}
                                    <tr>
                                        <td>{{ crit.id }}</td>                                                         
                                        <td>{% trans %}N°customer: {% endtrans %}{{ crit.user.id }}<br><hr>{{ crit.titreDiagnostic }}</td>                               
                                        <td>{{ crit.nbMCarre }}</td>                              
                                        <td>{{ crit.lieu }}</td>
                                        <td>{{crit.anneeConstr}}</td>                              
                                        <td><img src="../img/{{ crit.planLieu }}" alt="plan" class="imgdiagnostic"/></td>                              
                                        <td><img src="../img/{{ crit.photoLieu }}" alt="plan" class="imgdiagnostic"/></td>                              
                                        <td>{{ crit.orientation }}</td>
                                        {% if crit.diagnostic.statutExpertise is defined %}
                                        <td><i class="fas fa-check"></i></td>
                                        <td>Déjà validé</td>
                                        {% else %}
                                        <td><form method='POST' action="{{ path('diagnostic_ajouter', { id: crit.id }) }}" enctype="multipart/form-data"><input type='file' name='pdfExpertise' class='btnParcourir'/></form></td>
                                        <td><button type="button" class='valider'><a href="{{ path("diagnostic_ajouter", { id: crit.id }) }}">Valider</a></button></td>   
                                        {% endif %}                          
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/user/compte_user.html.twig
{% extends 'base.html.twig' %}

{% block title %} e-Feng Shui {% endblock %}

{% block body %}

<h2 class="titre">{% trans %}My account{% endtrans %}</h2>
<div class="flex-column-reverse">
  <div class="col-lg-12">
    <div class="card">
      <div class="card-body">
        <h3 class="card-title">{% trans %}My diagnostics {% endtrans %}</h3>
            <table class="table table-bordered">
            <thead>
                <tr>
                    <th>{% trans %}Diagnostic number{% endtrans %}</th><th>{% trans %}Date{% endtrans %}</th><th>{% trans %}Price{% endtrans %}</th><th>{% trans %}Expertise{% endtrans %}</th><th>{% trans %}Visualiser{% endtrans %}</th>
                </tr>
            </thead>
            {% for critere in app.user.criteres %}
              {% if critere.diagnostic.id is defined %}
                <tr>
                    <td>{{ critere.diagnostic.id }}</td>
                    <td>{{ critere.diagnostic.date|date("d/m/Y") }} </td>
                    <td>{{ critere.diagnostic.prix }}</td>
                    <td><a href='../img/diagnostic.pdf' download='diactostic.pdf'><i class='fas fa-file-download'>{% trans %} Download your diagnostic{% endtrans %}</i></a></td>
                    <td><a href='#'><i class='fas fa-eye'></i></a></td>
                </tr>
              {% endif %}
            {% endfor %}
            <tfoot>
            </tfoot>
            </table>
      </div>
    </div>
  </div>
  <div class="col-lg-12">
    <div class="card">
      <div class="card-body">
        <h3 class="card-title">{% trans %}My informations {% endtrans %}</h3>
            <div class="form-group">
                <label for="nom">{% trans %}My ID{% endtrans %}</label>
                <input type="text" class="form-control" id="id" name="id" value="{{ app.user.id}}">
            </div>
            <div class="form-group">
                <label for="nom">{% trans %}First name{% endtrans %}</label>
                <input type="text" class="form-control" id="nom" name="nom" value="{{ app.user.nom }}">
            </div>
            <div class="form-group">
                <label for="nom">{% trans %}Name{% endtrans %}</label>
                <input type="text" class="form-control" id="prenom" name="prenom" value="{{ app.user.prenom }}">
            </div>
            <a href="{{ path("user_modifier", {id: app.user.id}) }}" class="btn btn-dark">Modifier mon compte</a>
            <a href="{{ path("user_supprimer", {id: app.user.id}) }}" class="btn btn-dark">Supprimer mon Compte</a>
      </div>
    </div>
  </div>
</div>

{% endblock %}

templates/user/formulaire.html.twig
{% extends "base.html.twig" %}

{% block body %}

<h2 class="h2 text-center mt-3 mb-5">{% trans %}Modify a user{% endtrans %}</h2>

<div class="d-flex justify-content-center">
    <form class="col-md-6 text-center" method="post">
        <div class="form-group">
            <label for="nom">{% trans %}Name{% endtrans %}</label>
            <input type="text" class="form-control" id="nom" name="nom" value="{{ user is defined ? user.nom : "" }}">
        </div>
        <div class="form-group">
            <label for="nom">{% trans %}First name{% endtrans %}</label>
            <input type="text" class="form-control" id="prenom" name="prenom" value="{{ user is defined ? user.prenom : "" }}">
        </div>
        <div class="form-group">
            <label for="email">{% trans %}Email{% endtrans %}</label>
            <input type="text" class="form-control" id="email" name="email" value="{{ user is defined ? user.email : "" }}">
        </div>
        <div class="form-group">
            <label for="password"{% trans %}>Password{% endtrans %}</label>
            <input type="password" class="form-control" id="password" name="password" >
        </div>

    
        {% if bouton == "update" %}
            <button type="submit" name="submit" class="btn btn-success"><i class="fa fa-pen"></i></button>
        {% elseif bouton == "delete" %}
            <button type="submit" name="submit" class="btn btn-danger"><i class="fa fa-trash"></i></button>
        {% elseif bouton == "add" %}
            <button type="submit" name="submit" class="btn btn-dark"><i class="fa fa-save"></i></button>
        {% endif %}
    
    </form>
</div>


{% endblock %}

templates/user/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}e-Feng Shui{% endblock %}

{% block body %}

    <div id="contenuSubs">
        <h1 class="subsTitle">{% trans %}Sign up !{% endtrans %}</h1>

    {{ form_start(UserSubsForm) }}
        {{ form_row(UserSubsForm.nom) }}
        {{ form_row(UserSubsForm.prenom) }}
        {{ form_row(UserSubsForm.email) }}
        {{ form_row(UserSubsForm.password) }}
        {{ form_row(UserSubsForm.conditions) }}

        <button id="btnSubs">{% trans %}Sign me up{% endtrans %}</button>
        {{ form_row(UserSubsForm._token) }}
    {{ form_end(UserSubsForm) }}
    </div>

{% endblock %}

templates/user/liste.html.twig
{% extends 'base.html.twig' %}

{% block title %} e-Feng Shui {% endblock %}

{% block body %}

<h1>{% trans %}List of users{% endtrans %}</h1>
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>{% trans %}id{% endtrans %}</th><th>{% trans %}Name{% endtrans %}</th><th>{% trans %}Firstname{% endtrans %}</th><th>{% trans %}E-mail{% endtrans %}</th><th>{% trans %}Roles{% endtrans %}</th><th>{% trans %}Password{% endtrans %}</th>
                <th>{% trans %}Actions{% endtrans %}</th>
            </tr>
        </thead>
        {% for user in liste %}
            <tr>
                <td>{{ user.id }}</td>
                <td>{{ user.nom }}</td>
                <td>{{ user.prenom }}</td>
                <td>{{ user.email }}</td>
                <td>{{ user.roles|join(" , ") }}</td>
                <td>{{ user.password}}</td>
                <td><a href=""> <i class="fas fa-edit"></i> 
                <a href=""><i class="fa fa-trash"></i></a></td>   
            </tr>
        {% endfor %}
        <tfoot>
        </tfoot>
    </table>
{% endblock %}

templates/user/modif_user.html.twig
{% extends 'base.html.twig' %}

{% block title %}Efengshui{% endblock %}

{% block body %}

<h2 class="h2 text-center mt-3 mb-5">{% trans %}Modify my acocunt{% endtrans %}</h2>

<div class="d-flex justify-content-center">
    <form class="col-md-6 text-center" method="post">
        <div class="form-group">
            <label for="nom">{% trans %}Name{% endtrans %}</label>
            <input type="text" class="form-control" id="nom" name="nom" value="{{ user is defined ? user.nom : "" }}">
        </div>
            <div class="form-group">
            <label for="nom">{% trans %}First name{% endtrans %}</label>
            <input type="text" class="form-control" id="prenom" name="prenom" value="{{ user is defined ? user.prenom : "" }}">
        </div>
        <div class="form-group">
            <label for="password">{% trans %}Password{% endtrans %}</label>
            <input type="password" class="form-control" id="password" name="password" >
        </div>

   <button type="submit" name="submit" class="btn btn-dark">{% trans %}Modify{% endtrans %}</button>
    </form>

</div>

{% endblock %}

templates/user/supprimer_user.html.twig
{% extends 'base.html.twig' %}

 


{% block title %}e-Feng Shui{% endblock %}



{% block body %}


    
    {% for message in app.flashes('info') %}
    <div class="alert alert-info" role="alert">
    {{ message}}

    </div 
    {% endfor %}

<button><a href="{{ path("accueil") }}" class="btn btn-dark" onclick="return confirm('Votre compte a bien été supprime')">Confirmer</a></button>
 
{% endblock %}